include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - prefer_const_constructors
    - prefer_const_literals_to_create_immutables
    - avoid_print
    - prefer_single_quotes
    - prefer_final_fields
    - unnecessary_null_checks
    - use_key_in_widget_constructors
